project_id = "jsuqipnblmjayovklhrf"

[functions.chat]
verify_jwt = false

[functions.test-openai]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-text]
verify_jwt = false